server:
  port: 8081
spring:
  datasource:
        url: jdbc:mysql://192.168.0.153:3306/basic?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

  http:
      encoding:
        force: true

  #spingboot配置redis
  redis:
    database: 0
    host: 192.168.0.153
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    password: 123456
    port: 6379

  #ActiveMq消息队列
  activemq:
      user: admin
      password: admin
      broker-url: tcp://192.168.0.153:61616
      pool:
        enabled: true
        max-connections: 10

  mail:
    protocol: smtp #smtp是邮件发送协议，pop3和imap是邮件接收协议。因为我们要发送邮件，因此是smtp
    host: smtp.qq.com #邮件发送服务器的主机，这里采用的是qq邮箱来发送邮件
    port: 25 #邮件发送服务器的端口
    auth: true #一般情况下，发送邮件都是要进行验证
    username: 1164760152@qq.com
    password: wpaopdhsjefojagc


  boot:
    admin:
      client:
        prefer-ip: true
      url: http://localhost:8081


mybatis:
  type-aliases-package: cc.basic.mapper
  mapper-locations: classpath*:mapper/*.xml # 所有的mapper映射文件
  check-config-location: true


logging:
  level:
      cc.basic.mapper: debug
  config: classpath:log4j2.yml

queueName: publish.queue
topicName: publish.topic

