server:
  port: 8081
spring:
  datasource:
        url: jdbc:mysql://127.0.0.1:3306/basic?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

  http:

      encoding:
        force: true


  boot:
    admin:
      client:
        prefer-ip: true
      url: http://localhost:8081


mybatis:
  type-aliases-package: cc.basic.mapper
  mapper-locations: classpath*:mapper/*.xml # 所有的mapper映射文件
  check-config-location: true


logging:
  level:
      cc.basic.mapper: debug
  config: classpath:log4j2.yml


